### ISSUE TITLE
solr-conf

### ISSUE THREAD

**Issue by wacharlin** [DmitryKey/bert-solr-search#10]
hi,could you please provide a config (including managed-schema and solrconfig.xml) version about solr7.2.0?  i don't know how to config it and i want to ask you for help. thank you.

**Comment by DmitryKey** [comment]
hey @wacharlin I recommend you to do the following (should be quite straightforward):

1. download solr 7.2.0 from Apache archives and create a new core.
2. in the existing core, make modifications to schema and solrconfig according to https://github.com/DmitryKey/bert-solr-search#preprocessing-and-indexing-solr If something is missing, please create a PR!
3. Build solr-vector-scoring plugin using the closest release: https://github.com/DmitryKey/solr-vector-scoring/releases/tag/7.3.0
