### ISSUE TITLE
elastiknn_unsupported_operation_exception

### ISSUE THREAD

**Issue by anasben7** [DmitryKey/bert-solr-search#13]
Hello Dmitry! I've read your blog on Medium, and your work really helped me to make our search system smarter!
I've implemented SBERT and ElastiKNN to our system, and the results are amazing!
I only have a bug/problem with my index pattern in Kibana when using Elastiknn type elastiknn_dense_float_vector.
Where I create an index pattern, and I go to the "discover" tab in Kibana, I got this error:

<img width="668" alt="Screen Shot 2021-04-13 at 14 52 20" src="https://user-images.githubusercontent.com/48560744/114574413-c163b100-9c68-11eb-9c60-c2305fb1a0bf.png">

Do you have any leads on how can I fix this?
And again, thanks a lot Dmitry for sharing your experience with us in your blog/Github.

**Comment by DmitryKey** [comment]
hello @anasben7 somehow github did not notify me in time -- I'm sorry to have missed your question.

Really glad to hear, that my work has helped you implement more relevant search!

On your question -- I can guess that kibana does not support this special field type, implemented by elastiknn. That is why you can't run kibana-specific tooling on it. But I suspect Elasticsearch itself offers APIs to maintain index patterns.
