### ISSUE TITLE
Streamlit JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by xeisberg** [DmitryKey/bert-solr-search#14]
Dear @DmitryKey , it is a pleasure to follow your guides and go through the examples. Thank you for providing such interesting tools. 

Concerning "Neural Search with BERT and Solr" everything seems to go alright including indexing and searching on the solr server, however, once I start streamlit the following errors occur when I search. Do you have any idea about what it may be? 

```
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback:

File "/home/n/documents/my_jina_app/baas/env/lib/python3.6/site-packages/streamlit/script_runner.py", line 337, in _run_script
    exec(code, module.__dict__)
File "/home/n/documents/my_jina_app/baas/bert-solr-search/src/search_demo_solr.py", line 122, in <module>
    docs, query_time, numfound = sc.query("vector", query)
File "src/client/solr_client.py", line 102, in query
    resp = resp.json()
File "/home/n/documents/my_jina_app/baas/env/lib/python3.6/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
File "/home/n/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
File "/home/n/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/home/n/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
 ```

Thank you for your consideration.

**Comment by DmitryKey** [comment]
Hi @xeisberg 
Thank you for kind words and glad to hear that the tools are interesting to you.

For the error above -- do you see any errors in Solr's logs?
Does the index exist and it contains the `vector` field?

Can you please paste the screenshot of the streamlit UI, since it has few params -- so it will be easier to reproduce on my side.

**Comment by xeisberg** [comment]
Dear @DmitryKey . Thank you for taking the time to consider my issue. I should also mention that I am using solr 8.5.2 with this plugin version https://github.com/markhng525/solr-vector-scoring

I did try solr 6.6.0 and 8.8.0 following your instructions and ended up with the same error while using streamlit although indexing worked fine. I have not saved the error logs but can quickly do so as I have kept the folders intact and easy to run. 

solr logging looks like this:
![image](https://user-images.githubusercontent.com/81804071/117386224-7ebc8e00-af21-11eb-8a59-709994298cd8.png)


I think the indexing is working fine as can be seen in this screenshot with the vector:

![image](https://user-images.githubusercontent.com/81804071/117385294-c7734780-af1f-11eb-9a8c-18709ccd1a33.png)
However, if I run "defType=vp" for the vector function I get the following error:
![image](https://user-images.githubusercontent.com/81804071/117385626-6b5cf300-af20-11eb-9bdc-acd44e1fa704.png)
`{
  "responseHeader":{
    "status":500,
    "QTime":0,
    "params":{
      "q":"*:*",
      "defType":"vp",
      "wt":"json",
      "debugQuery":"on",
      "_":"1620351183292"}},
  "error":{
    "trace":"java.lang.NullPointerException\n\tat com.github.saaay71.solr.query.VectorQParserPlugin$1.parse(VectorQParserPlugin.java:34)\n\tat org.apache.solr.search.QParser.getQuery(QParser.java:174)\n\tat org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:161)\n\tat org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:309)\n\tat org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:211)\n\tat org.apache.solr.core.SolrCore.execute(SolrCore.java:2596)\n\tat org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:802)\n\tat org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:579)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:420)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:352)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1596)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)\n\tat org.eclipse.jetty.server.handler.InetAccessHandler.handle(InetAccessHandler.java:177)\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)\n\tat org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:322)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:500)\n\tat org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)\n\tat org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)\n\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)\n\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)\n\tat org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)\n\tat org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)\n\tat java.lang.Thread.run(Thread.java:748)\n",
    "code":500}}`


Here are some screenshots of the streamlit UI. It does not work with any of the parameter settings that I have tried.

![image](https://user-images.githubusercontent.com/81804071/117384997-22f10580-af1f-11eb-86a1-cb3ecbc4396f.png)
![image](https://user-images.githubusercontent.com/81804071/117385033-34d2a880-af1f-11eb-9d79-54fd6ea3e28e.png)
![image](https://user-images.githubusercontent.com/81804071/117385084-5469d100-af1f-11eb-8f36-58e14d8dd8d8.png)

**Comment by DmitryKey** [comment]
hey @xeisberg it occurred to me: what version of the vector jar are you using? It might be you need to compile and configure the 8.x version: 
https://github.com/DmitryKey/solr-vector-scoring/releases/tag/8.0.0
Did you already try it?

Also https://github.com/DmitryKey/solr-vector-scoring has the instruction for sending the POST request to Solr to find similar vectors:

    {!vp f=vector vector="0.1,4.75,0.3,1.2,0.7,4.0"}

So you can first try this approach using curl or Postman for instance -- and if that works, then turn to the streamlit app.

Also, are using the master branch?

**Comment by xeisberg** [comment]
Hello @DmitryKey . I tried using the jar file from the master branch later on the 8.5.2 version and your 8.0.0 by creating it with `mvn package` .

Those queries seem to work fine; I tried with different values and it works.

![image](https://user-images.githubusercontent.com/81804071/117620533-84c59f80-b1ab-11eb-972f-ac92544c2c25.png)

![image](https://user-images.githubusercontent.com/81804071/117620592-96a74280-b1ab-11eb-98a5-a86f7d2bca71.png)

Do you mean the master branch of the solr vector scoring?

The streamlit error remains:

` 
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback:

File "/home/n/documents/my_jina_app/baas/env/lib/python3.6/site-packages/streamlit/script_runner.py", line 337, in _run_script
    exec(code, module.__dict__)
File "/home/n/documents/my_jina_app/baas/cbert/src/search_demo_solr.py", line 122, in <module>
    docs, query_time, numfound = sc.query("vector", query)
File "src/client/solr_client.py", line 102, in query
    resp = resp.json()
File "/home/n/documents/my_jina_app/baas/env/lib/python3.6/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
File "/home/n/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
File "/home/n/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/home/n/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None 
`

By the way, the vectors look a bit different in the solr admin page:

![image](https://user-images.githubusercontent.com/81804071/117620999-103f3080-b1ac-11eb-95f6-15040a218cca.png)


I beg your pardon for all the troubles and thank you for your assistance.

**Comment by DmitryKey** [comment]
Can you consider testing https://github.com/DmitryKey/solr-vector-scoring/releases/tag/8.0.0 version?
I'm trying to repro the issue on my side

**Comment by xeisberg** [comment]
@DmitryKey Thank you. I beg your pardon for not being clear in the last message. I tried with the Solr 6.6.0, 8.0.0, and 8.5.2 with their respective plugins hoping to solve the problem.

Anyway, I tried again now creating a new jar plug using mvn package from your link and used it with Solr 8.0.0 and the same error occurs as before. The beforementioned queries functions well in the browser so I wonder what the problem could be.

**Comment by DmitryKey** [comment]
hi @xeisberg let's compare the python dependencies. Can you please run 
`pip freeze > requirements_freeze.txt`
and then compare this file with the same file in git? https://github.com/DmitryKey/bert-solr-search/blob/feature/odfe-1M-indexing-optimization/requirements_freeze.txt


And the other thing -- can you compare your managed_schema and solrconfig.xml to these: https://github.com/DmitryKey/bert-solr-search/tree/feature/odfe-1M-indexing-optimization/solr_conf/8.0.0

**Comment by xeisberg** [comment]
Hello @DmitryKey .
In the virtual environment I installed your requirements_freeze.txt so the only package not the same when comparing was :

53 | ipython | 7.17.0 | 7.16.1, could this be a problem?

The configs are 100% match. 

Given that the query is working with http://localhost:8983/solr/vector_10/query?fl=name,score,vector&q={!vp f=vector [..], is it possible to query is some other way without going through streamlit? Of course this not fully related to this issue.

**Comment by DmitryKey** [comment]
thanks for checking that!

How many dimensions do your vectors have?
In my case I use 768 dim vectors, so the only way to query them is to use HTTP POST, because the character length of the query exceeds HTTP GET.

Btw, would you be open for a quick zoom call to show your vector search setup? It might be a little faster to figure things out.
Ok, if not: we can also continue discussing here!

**Comment by xeisberg** [comment]
@DmitryKey I see. I am not sure how to check the dimensions of the vectors. I am using BERT uncased_L-4_H-128_A-2.

For sure. If you send me a like or another way of contacting you I could join you. When would it suit you?

**Comment by DmitryKey** [comment]
@xeisberg I've sent you a zoom link for tomorrow, hope it works out for you.

**Comment by DmitryKey** [comment]
Looking at your model name, I believe it is generating 128 dimensional vectors. You can double check that by looking inside the unziped directory with the model, look for config.json and parameter name is `hidden_size`.

**Comment by xeisberg** [comment]
@DmitryKey Thank you. Speak to you later today. Indeed, it has 128 dimensional vectors as specified in the config. Thank you for clarifying.

**Comment by xeisberg** [comment]
Thank you for the assistance @DmitryKey.

So in the end the problem was the src/search_demo_solr.py file
on line 122 :      `docs,query_time, numfound = sc.query("vector", query)` where one needs to replace "vector" with the core name in your solr index which may be determined by the amount of files that one indexes(it my case it became vector_10 for 10 files.
