### ISSUE TITLE
problems for

### ISSUE THREAD

**Issue by wacharlin** [DmitryKey/bert-solr-search#5]
![image](https://user-images.githubusercontent.com/38215077/112092756-1e70c780-8bd3-11eb-8ce6-5a0dd1fd63b9.png)
 to run the command "bash start_bert_server.sh" , i find the problems,i want to know how to solve it ? thank you

**Comment by DmitryKey** [comment]
hey @wacharlin have you installed the bert-as-service? You can check the https://github.com/DmitryKey/bert-solr-search/blob/master/README.md

**Comment by wacharlin** [comment]
> hey @wacharlin have you installed the bert-as-service? You can check the https://github.com/DmitryKey/bert-solr-search/blob/master/README.md

thanks,i run the code before 

> hey @wacharlin have you installed the bert-as-service? You can check the https://github.com/DmitryKey/bert-solr-search/blob/master/README.md

thank you.but now i get a new problem.i use the gpu to run the code and use xshell to connect the gpu.i dont' understand the solr.i wget the solr and then run the command“streamlit run src/search_demo_solr.py”.but it says 
![image](https://user-images.githubusercontent.com/38215077/112247063-9223da80-8c8e-11eb-8bf4-657a441b072c.png)

is this right and how to view the result? thank you.

**Comment by wacharlin** [comment]
> hey @wacharlin have you installed the bert-as-service? You can check the https://github.com/DmitryKey/bert-solr-search/blob/master/README.md

![image](https://user-images.githubusercontent.com/38215077/112271026-5cdeb300-8cb5-11eb-825f-3294592f404c.png)
thank you,i solved the problems use root .and i have run it in my win10 OS ,but there is a new problem about connection and i want to know how to solve it? thank you.

**Comment by wacharlin** [comment]
thank you  @DmitryKey. but now i get a problem again.i don't know solr.so i want to know that after i start solr,how to index in solr? i just run the command "bin/solr start -m 2g" and  directly run the demo code "streamlit run src/search_demo_solr.py".but there is a problem.i guess the problem is that i don't index them in solr.so i want to know how to solve it and i ask help for you. hope you reply.thank you
![image](https://user-images.githubusercontent.com/38215077/112279247-ae3f7000-8cbe-11eb-8aa4-e2ab768a01f7.png)
![image](https://user-images.githubusercontent.com/38215077/112279259-b4355100-8cbe-11eb-9a5b-f4add0b3b14b.png)

**Comment by DmitryKey** [comment]
btw, thank you for poking around -- README definitely needs improvements. I have just added the bit about the plugin.
