### ISSUE TITLE
the problem of solr

### ISSUE THREAD

**Issue by wacharlin** [DmitryKey/bert-solr-search#6]
hi,i want to know how to index in the solr?because after starting solr,i put the file  "solr_conf/8.0.0"  replace my own file."solrconfig.xml" and "managed-schema".but i get the wrong and i don't know if the step is right.so i want to ask you to know how to config the solr?could you help me to solve the problem?thank you. 
![image](https://user-images.githubusercontent.com/38215077/112560139-7b57c200-8e0d-11eb-8763-b7b35ff8a1f6.png)

**Comment by DmitryKey** [comment]
@wacharlin did you figure this out? You need to add a custom plugin to Solr's lib directory: https://github.com/DmitryKey/solr-vector-scoring

**Comment by wacharlin** [comment]
> @wacharlin did you figure this out? You need to add a custom plugin to Solr's lib directory: https://github.com/DmitryKey/solr-vector-scoring

thank you! i figured it out because i found the url you provided.but now i have meet the problem that i don't know how to do.i ask you in the new problem i want to receive your reply.
