### ISSUE TITLE
problem for indexing the abstracts.

### ISSUE THREAD

**Issue by wacharlin** [DmitryKey/bert-solr-search#7]
hi,i run the code "python src/index_dbpedia_abstracts_solr.py",because i don't find the code"index_dbpedia_abstracts.py".
the function "parse_dbpedia_data" have two params,but here you give five. so how to solve it?
![image](https://user-images.githubusercontent.com/38215077/112712469-c4da0700-8f0a-11eb-9fa2-99a0215d3c40.png)
![image](https://user-images.githubusercontent.com/38215077/112712472-cc99ab80-8f0a-11eb-97fb-d1cb0b3eb1ad.png)

**Comment by wacharlin** [comment]
the sentence "from data_utils import parse_dbpedia_data, EmbeddingModel, SearchEngine" cause the problem.so i want to know how to solve it? thank you. hope to receive your reply.

**Comment by DmitryKey** [comment]
great find! Let me fix this.

**Comment by wacharlin** [comment]
Hi,I don't find the file "index_dbpedia_abstracts.py" and I don't find the showing on the graph. I want to know  how to run?
I run the "src/index_dbpedia_abstracts_solr.py" and it doesn’t take long to run like you said.although they can load in solr,this is the field.but I did not find the field you showed. What can I do? thank you. I hope to receive your answers, please...please...
![image](https://user-images.githubusercontent.com/38215077/112743169-99692200-8fc7-11eb-94b5-83e19a59d717.png)
![image](https://user-images.githubusercontent.com/38215077/112743264-3a57dd00-8fc8-11eb-8307-f295fbe661c7.png)
![image](https://user-images.githubusercontent.com/38215077/112743280-6a06e500-8fc8-11eb-91cc-86340a58d305.png)

**Comment by wacharlin** [comment]
oh,I'm sorry to disturb you.I want to know that could you please help me to index the abstract in the solr?Because I don't find the file like you said --"index_dbpedia_abstracts.py".and I can't index abstract in the solr.
I ran the file--“src/index_dbpedia_abstracts_solr.py” and it was done quickly. It didn't take as long as you said. But I opened Solr and looked at it, and the vector field was not stored. I compared these screenshots with yours in the comments above. I want to know why? Can you help me solve it?I want you to talk about the steps in detail.Thank you.
![image](https://user-images.githubusercontent.com/38215077/112743894-e8b25100-8fcd-11eb-921b-1636e08c2b53.png)

**Comment by DmitryKey** [comment]
hey @wacharlin I made a push to master: please try `src/index_dbpedia_abstracts_solr.py`

the script `src/index_dbpedia_abstracts.py` does not exist anymore -- it became `src/index_dbpedia_abstracts_solr.py`. I will edit the blog and README.

**Comment by wacharlin** [comment]
> hey @wacharlin I made a push to master: please try `src/index_dbpedia_abstracts_solr.py`
> 
> the script `src/index_dbpedia_abstracts.py` does not exist anymore -- it became `src/index_dbpedia_abstracts_solr.py`. I will edit the blog and README.

i read the code that maybe you use the docker.could you please give a code that running in my localhost? thank you.

**Comment by DmitryKey** [comment]
* What version of Solr are you running?
* Have you configured the vector jar plugin into your Solr? You need to build the jar using maven in this project: https://github.com/DmitryKey/solr-vector-scoring

**Comment by wacharlin** [comment]
> * What version of Solr are you running?
> * Have you configured the vector jar plugin into your Solr? You need to build the jar using maven in this project: https://github.com/DmitryKey/solr-vector-scoring

my solr is 6.6.0. thank you for your reply. I modified some code to run in my localhost. Thank you.
From the beginning to the end, my problem was that the vector was not saved in Solr. so there are so many problems.Thank you for this version of the code for some enlightenment, and then I changed it in the previous version. The demo has been successfully ran through. Thank you again, thank you for answering my questions for so many days.
May I ask you some questions about information retrieval in the future? If possible, can you share your email? thank you !

**Comment by DmitryKey** [comment]
you're welcome @wacharlin 
Since I do this work in my free time, it is best if you reach out to me in a specific issue or in the Discussion: https://github.com/DmitryKey/bert-solr-search/discussions
