### ISSUE TITLE
Typo in create_gsi_files.py

### ISSUE THREAD

**Issue by nina-marjanovic** [DmitryKey/bert-solr-search#9]
There is a small typo in https://github.com/DmitryKey/bert-solr-search/blob/master/src/create_gsi_files.py with `vectors_to_gis_files` which prevents one from running the script.
`vectors_to_gsi_files` should be imported and called.

**Comment by DmitryKey** [comment]
Hey @nina-marjanovic thanks for reporting! If you'd like you can send a pull request and get credit for it!
Otherwise I will fix in a bit.

**Comment by nina-marjanovic** [comment]
Hi, @DmitryKey!
No problem! 🙂 And thank you, but please feel free to fix it, it's just a tiny mistake.

**Comment by DmitryKey** [comment]
hey @nina-marjanovic I've pushed the fix into new branch. Will close this ticket for now, thanks for testing and spotting the typo! :)
